
title = "c332030"
baseURL = "https://c332030.com/"
languageCode = "zh"
theme = "stack"

DefaultContentLanguage = "zh"
SectionPagesMenu = "main"
Paginate = 9
googleAnalytics = "UA-155324421-2"
enableRobotsTXT = true

[sitemap]
changefreq = "daily"
priority = 0.5
filename = "sitemap.xml"

[params]
favicon = "favicon.ico"
site_logo = ""
description = "c332030"
facebook = ""
twitter = ""
instagram = ""
youtube = ""
github = "https://github.com/c332030"
gitlab = ""
linkedin = ""
mastodon = ""
slack = ""
stackoverflow = ""
rss = ""

# choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-black"
featured_image = ""
recent_posts_number = 3
