
name: hugo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  hugo:
    runs-on: ubuntu-latest
    steps:
      - uses: c332030/hugo-asciidoctor-action@1.0.0
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          USER: ${{ github.actor }}
          EMAIL: ${{ github.actor }}@gmail.com
          COMMAND: ${{ secrets.COMMAND }}
        with:
          source-repo: git@github.com:${{ github.repository_owner }}/${{ github.event.repository.name }}.git
          build-repo: git@github.com:${{ github.repository_owner }}/${{ github.repository_owner }}.github.io.git
